services: 
  server:
    image: panubo/vsftpd:latest
    container_name: server
    ports:
      - "5050:21"
    environment:
      - FTP_USER=user
      - FTP_PASSWORD=pass
    volumes:
      - ./ftp/data:/srv
    networks:
      - inquisitor
    restart: always
    
  client:
    image: jlesage/filezilla
    container_name: client
    ports:
      - "5800:5800"
    volumes:
      - ./ftp_files:/storage:rw
    logging:
      driver: none
    networks:
      - inquisitor
    
  arp_spoofer:
    build: .
    container_name: arp_spoofer
    environment:
      CLIENTIP: ${CLIENTIP}
      CLIENTMAC: ${CLIENTMAC}
      SERVERIP: ${SERVERIP}
      SERVERMAC: ${SERVERMAC}
    networks:
      - inquisitor
    depends_on:
      - client
      - server
    restart: always

networks:
  inquisitor:
    driver: bridge
